version: '3'

services:
  db:
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33060:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"

