@startuml
left to right direction

[Browser]
cloud "Aws" {

    package "Aws S3\nConteúdo estático" {
        [SPA Front-end]
    }

    package "AWS Elastic Beanstalk"{
        [Rails - Graphql API]
     
        database "RDS - MySql" {
            [EventPlanner DB]
        }
    }
    
    [AWS SNS]
}

[Browser] --> [SPA Front-end] :Http/Https
[SPA Front-end] --> [Rails - Graphql API] : Graphql/Http
[Rails - Graphql API] --> [EventPlanner DB]
[Rails - Graphql API] -->  [AWS SNS]
@enduml
