@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/react.puml
!include DEVICONS/ruby_on_rails.puml
!include DEVICONS/mysql.puml
!include DEVICONS/aws.puml
!include FONTAWESOME/users.puml

HIDE_STEREOTYPE()

Person(organizador, "Organizador do evento", "Responsável pela criação e planejamento dos eventos")
Person(lider, "Líder de equipe", "Responsável pela gestão e escala de sua equipe")
Person(membros, "Membros de equipe", "Usuários escalados para eventos",  $sprite="users")

System(spe, "Sistema de Planejamento de Eventos", "Permite a configuração dos eventos, equipes e escalas.")
System_Ext(sns, "Sistema de notificações", "Envia notificações para os usuarios via mensagem de texto (SMS) ou Email")

Rel(organizador, spe, "Cria os eventos, equipes e escalas")
Rel(lider, spe, "Gerencia sua equipe e escalas")
Rel(membros, spe, "Responde a escalação dos eventos, visualiza escala")
Rel_R(spe, sns, "Envia notificações")

@enduml
